const UserActionTypes = {
	GOOGLE_SIGN_IN_START: 'SIGN_IN_START',
	EMAIL_SIGN_IN_START: 'EMAIL_IN_START',
	SIGN_IN_SUCCESS: 'IN_SUCCESS',
	SIGN_IN_FAILURE: 'IN_FAILURE',
};

export default UserActionTypes;
